// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lorenz_cpp
NumericMatrix lorenz_cpp(NumericVector x0, double sigma, double rho, double beta, double dt, int n, int thin, int precision);
RcppExport SEXP _chaosrcpp_lorenz_cpp(SEXP x0SEXP, SEXP sigmaSEXP, SEXP rhoSEXP, SEXP betaSEXP, SEXP dtSEXP, SEXP nSEXP, SEXP thinSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(lorenz_cpp(x0, sigma, rho, beta, dt, n, thin, precision));
    return rcpp_result_gen;
END_RCPP
}
// roessler_cpp
NumericMatrix roessler_cpp(NumericVector x0, double a, double b, double c, double dt, int n, int thin, int precision);
RcppExport SEXP _chaosrcpp_roessler_cpp(SEXP x0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dtSEXP, SEXP nSEXP, SEXP thinSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(roessler_cpp(x0, a, b, c, dt, n, thin, precision));
    return rcpp_result_gen;
END_RCPP
}
// lorenz_lyapunov_cpp
NumericVector lorenz_lyapunov_cpp(NumericVector x0, double sigma, double rho, double beta, double dt, int n, int n_transient);
RcppExport SEXP _chaosrcpp_lorenz_lyapunov_cpp(SEXP x0SEXP, SEXP sigmaSEXP, SEXP rhoSEXP, SEXP betaSEXP, SEXP dtSEXP, SEXP nSEXP, SEXP n_transientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    rcpp_result_gen = Rcpp::wrap(lorenz_lyapunov_cpp(x0, sigma, rho, beta, dt, n, n_transient));
    return rcpp_result_gen;
END_RCPP
}
// roessler_lyapunov_cpp
NumericVector roessler_lyapunov_cpp(NumericVector x0, double a, double b, double c, double dt, int n, int n_transient);
RcppExport SEXP _chaosrcpp_roessler_lyapunov_cpp(SEXP x0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dtSEXP, SEXP nSEXP, SEXP n_transientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    rcpp_result_gen = Rcpp::wrap(roessler_lyapunov_cpp(x0, a, b, c, dt, n, n_transient));
    return rcpp_result_gen;
END_RCPP
}
// dd_selftest_cpp
NumericVector dd_selftest_cpp(double a, double b);
RcppExport SEXP _chaosrcpp_dd_selftest_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dd_selftest_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// logistic_orbit_cpp
NumericVector logistic_orbit_cpp(double x0, double r, int n);
RcppExport SEXP _chaosrcpp_logistic_orbit_cpp(SEXP x0SEXP, SEXP rSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_orbit_cpp(x0, r, n));
    return rcpp_result_gen;
END_RCPP
}
// logistic_bifurcation_cpp
List logistic_bifurcation_cpp(NumericVector r, double x0, int n_transient, int n_keep);
RcppExport SEXP _chaosrcpp_logistic_bifurcation_cpp(SEXP rSEXP, SEXP x0SEXP, SEXP n_transientSEXP, SEXP n_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    Rcpp::traits::input_parameter< int >::type n_keep(n_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_bifurcation_cpp(r, x0, n_transient, n_keep));
    return rcpp_result_gen;
END_RCPP
}
// logistic_lyapunov_cpp
NumericVector logistic_lyapunov_cpp(NumericVector r, double x0, int n_transient, int n);
RcppExport SEXP _chaosrcpp_logistic_lyapunov_cpp(SEXP rSEXP, SEXP x0SEXP, SEXP n_transientSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_lyapunov_cpp(r, x0, n_transient, n));
    return rcpp_result_gen;
END_RCPP
}
// henon_cpp
NumericMatrix henon_cpp(double x0, double y0, double a, double b, int n, int n_transient);
RcppExport SEXP _chaosrcpp_henon_cpp(SEXP x0SEXP, SEXP y0SEXP, SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP n_transientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    rcpp_result_gen = Rcpp::wrap(henon_cpp(x0, y0, a, b, n, n_transient));
    return rcpp_result_gen;
END_RCPP
}
// henon_bifurcation_cpp
List henon_bifurcation_cpp(NumericVector a, double b, double x0, double y0, int n_transient, int n_keep);
RcppExport SEXP _chaosrcpp_henon_bifurcation_cpp(SEXP aSEXP, SEXP bSEXP, SEXP x0SEXP, SEXP y0SEXP, SEXP n_transientSEXP, SEXP n_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    Rcpp::traits::input_parameter< int >::type n_keep(n_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(henon_bifurcation_cpp(a, b, x0, y0, n_transient, n_keep));
    return rcpp_result_gen;
END_RCPP
}
// ikeda_cpp
NumericMatrix ikeda_cpp(double x0, double y0, double u, int n, int n_transient);
RcppExport SEXP _chaosrcpp_ikeda_cpp(SEXP x0SEXP, SEXP y0SEXP, SEXP uSEXP, SEXP nSEXP, SEXP n_transientSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< double >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_transient(n_transientSEXP);
    rcpp_result_gen = Rcpp::wrap(ikeda_cpp(x0, y0, u, n, n_transient));
    return rcpp_result_gen;
END_RCPP
}
// standard_map_cpp
NumericMatrix standard_map_cpp(NumericVector theta0, NumericVector p0, double K, int n);
RcppExport SEXP _chaosrcpp_standard_map_cpp(SEXP theta0SEXP, SEXP p0SEXP, SEXP KSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(standard_map_cpp(theta0, p0, K, n));
    return rcpp_result_gen;
END_RCPP
}
// embed_cpp
NumericMatrix embed_cpp(NumericVector x, int m, int tau);
RcppExport SEXP _chaosrcpp_embed_cpp(SEXP xSEXP, SEXP mSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(embed_cpp(x, m, tau));
    return rcpp_result_gen;
END_RCPP
}
// recurrence_matrix_cpp
LogicalMatrix recurrence_matrix_cpp(NumericMatrix X, double eps, int norm);
RcppExport SEXP _chaosrcpp_recurrence_matrix_cpp(SEXP XSEXP, SEXP epsSEXP, SEXP normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type norm(normSEXP);
    rcpp_result_gen = Rcpp::wrap(recurrence_matrix_cpp(X, eps, norm));
    return rcpp_result_gen;
END_RCPP
}
// sample_distances_cpp
NumericVector sample_distances_cpp(NumericMatrix X, int n_pairs, int norm);
RcppExport SEXP _chaosrcpp_sample_distances_cpp(SEXP XSEXP, SEXP n_pairsSEXP, SEXP normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_pairs(n_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type norm(normSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_distances_cpp(X, n_pairs, norm));
    return rcpp_result_gen;
END_RCPP
}
// rqa_cpp
List rqa_cpp(NumericMatrix X, double eps, int norm, int lmin, int vmin, int theiler);
RcppExport SEXP _chaosrcpp_rqa_cpp(SEXP XSEXP, SEXP epsSEXP, SEXP normSEXP, SEXP lminSEXP, SEXP vminSEXP, SEXP theilerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type norm(normSEXP);
    Rcpp::traits::input_parameter< int >::type lmin(lminSEXP);
    Rcpp::traits::input_parameter< int >::type vmin(vminSEXP);
    Rcpp::traits::input_parameter< int >::type theiler(theilerSEXP);
    rcpp_result_gen = Rcpp::wrap(rqa_cpp(X, eps, norm, lmin, vmin, theiler));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_chaosrcpp_lorenz_cpp", (DL_FUNC) &_chaosrcpp_lorenz_cpp, 8},
    {"_chaosrcpp_roessler_cpp", (DL_FUNC) &_chaosrcpp_roessler_cpp, 8},
    {"_chaosrcpp_lorenz_lyapunov_cpp", (DL_FUNC) &_chaosrcpp_lorenz_lyapunov_cpp, 7},
    {"_chaosrcpp_roessler_lyapunov_cpp", (DL_FUNC) &_chaosrcpp_roessler_lyapunov_cpp, 7},
    {"_chaosrcpp_dd_selftest_cpp", (DL_FUNC) &_chaosrcpp_dd_selftest_cpp, 2},
    {"_chaosrcpp_logistic_orbit_cpp", (DL_FUNC) &_chaosrcpp_logistic_orbit_cpp, 3},
    {"_chaosrcpp_logistic_bifurcation_cpp", (DL_FUNC) &_chaosrcpp_logistic_bifurcation_cpp, 4},
    {"_chaosrcpp_logistic_lyapunov_cpp", (DL_FUNC) &_chaosrcpp_logistic_lyapunov_cpp, 4},
    {"_chaosrcpp_henon_cpp", (DL_FUNC) &_chaosrcpp_henon_cpp, 6},
    {"_chaosrcpp_henon_bifurcation_cpp", (DL_FUNC) &_chaosrcpp_henon_bifurcation_cpp, 6},
    {"_chaosrcpp_ikeda_cpp", (DL_FUNC) &_chaosrcpp_ikeda_cpp, 5},
    {"_chaosrcpp_standard_map_cpp", (DL_FUNC) &_chaosrcpp_standard_map_cpp, 4},
    {"_chaosrcpp_embed_cpp", (DL_FUNC) &_chaosrcpp_embed_cpp, 3},
    {"_chaosrcpp_recurrence_matrix_cpp", (DL_FUNC) &_chaosrcpp_recurrence_matrix_cpp, 3},
    {"_chaosrcpp_sample_distances_cpp", (DL_FUNC) &_chaosrcpp_sample_distances_cpp, 3},
    {"_chaosrcpp_rqa_cpp", (DL_FUNC) &_chaosrcpp_rqa_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_chaosrcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
