# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lorenz_cpp <- function(x0, sigma, rho, beta, dt, n, thin, precision) {
    .Call(`_chaosrcpp_lorenz_cpp`, x0, sigma, rho, beta, dt, n, thin, precision)
}

roessler_cpp <- function(x0, a, b, c, dt, n, thin, precision) {
    .Call(`_chaosrcpp_roessler_cpp`, x0, a, b, c, dt, n, thin, precision)
}

lorenz_lyapunov_cpp <- function(x0, sigma, rho, beta, dt, n, n_transient) {
    .Call(`_chaosrcpp_lorenz_lyapunov_cpp`, x0, sigma, rho, beta, dt, n, n_transient)
}

roessler_lyapunov_cpp <- function(x0, a, b, c, dt, n, n_transient) {
    .Call(`_chaosrcpp_roessler_lyapunov_cpp`, x0, a, b, c, dt, n, n_transient)
}

dd_selftest_cpp <- function(a, b) {
    .Call(`_chaosrcpp_dd_selftest_cpp`, a, b)
}

logistic_orbit_cpp <- function(x0, r, n) {
    .Call(`_chaosrcpp_logistic_orbit_cpp`, x0, r, n)
}

logistic_bifurcation_cpp <- function(r, x0, n_transient, n_keep) {
    .Call(`_chaosrcpp_logistic_bifurcation_cpp`, r, x0, n_transient, n_keep)
}

logistic_lyapunov_cpp <- function(r, x0, n_transient, n) {
    .Call(`_chaosrcpp_logistic_lyapunov_cpp`, r, x0, n_transient, n)
}

henon_cpp <- function(x0, y0, a, b, n, n_transient) {
    .Call(`_chaosrcpp_henon_cpp`, x0, y0, a, b, n, n_transient)
}

henon_bifurcation_cpp <- function(a, b, x0, y0, n_transient, n_keep) {
    .Call(`_chaosrcpp_henon_bifurcation_cpp`, a, b, x0, y0, n_transient, n_keep)
}

ikeda_cpp <- function(x0, y0, u, n, n_transient) {
    .Call(`_chaosrcpp_ikeda_cpp`, x0, y0, u, n, n_transient)
}

standard_map_cpp <- function(theta0, p0, K, n) {
    .Call(`_chaosrcpp_standard_map_cpp`, theta0, p0, K, n)
}

embed_cpp <- function(x, m, tau) {
    .Call(`_chaosrcpp_embed_cpp`, x, m, tau)
}

recurrence_matrix_cpp <- function(X, eps, norm) {
    .Call(`_chaosrcpp_recurrence_matrix_cpp`, X, eps, norm)
}

sample_distances_cpp <- function(X, n_pairs, norm) {
    .Call(`_chaosrcpp_sample_distances_cpp`, X, n_pairs, norm)
}

rqa_cpp <- function(X, eps, norm, lmin, vmin, theiler) {
    .Call(`_chaosrcpp_rqa_cpp`, X, eps, norm, lmin, vmin, theiler)
}

